name: 'Veracode Connect'
description: 'Orquestra integrações do Veracode (Pipeline Scan, Upload & Scan, SCA, IaC/Secrets) com suporte opcional a baseline via Bantuu. Requer permissions: contents: read'
author: 'Afrika-Tecnologia'
branding:
  icon: 'shield'
  color: 'purple'

inputs:
  bantuu_api_key:
    description: 'API Key usada no header X-API-Key do Bantuu (GET baseline e POST upload).'
    required: false
  bantuu_base_url:
    description: 'URL base do Bantuu (sem barra final).'
    required: false
    default: 'https://www.bantuu.io'
  enable_sca:
    description: 'Ativa/desativa o Veracode SCA (true/false).'
    required: false
    default: 'false'
  veracode_sca_token:
    description: 'Token de API do Veracode SCA (usado quando enable_sca = true).'
    required: false
  enable_iac:
    description: 'Ativa/desativa o Veracode IaC/Secrets (directory scan) (true/false).'
    required: false
    default: 'false'
  enable_pipelinescan:
    description: 'Ativa/desativa o Veracode Pipeline Scan (true/false).'
    required: false
    default: 'true'
  enable_upload_scan:
    description: 'Ativa/desativa o Veracode Upload & Scan (true/false).'
    required: false
    default: 'false'
  enable_baseline:
    description: 'Ativa/desativa o fluxo de baseline do Bantuu (true/false).'
    required: false
    default: 'true'
  enable_auto_packager:
    description: 'Ativa/desativa o uso do Veracode Auto Packager antes do scan (true/false).'
    required: false
    default: 'false'
  veracode_api_id:
    description: 'ID da API do Veracode.'
    required: true
  veracode_api_key:
    description: 'Key da API do Veracode.'
    required: true
  veracode_sandbox:
    description: 'Define se o Upload & Scan deve usar sandbox (true) ou o app principal (false).'
    required: false
    default: 'true'
  scan_file:
    description: 'Arquivo compactado enviado ao Pipeline Scan (ex.: app.zip). Usado quando o auto packager está desativado.'
    required: false
  policy_fail:
    description: 'Define se o scan deve quebrar o build por policy (true/false).'
    required: false
    default: 'false'
  fail_on_severity:
    description: 'Severidades que fazem o scan falhar quando há baseline (ex.: "Very High, High").'
    required: false
  fail_build:
    description: 'Se true, o build falha caso qualquer scan reporte erro. Se false, apenas emite warnings (true/false).'
    required: false
    default: 'true'
  veracode_appname:
    description: 'Nome do app no Veracode.'
    required: false
    default: '${{ github.repository }}'

  # Business Unit (aceita nomes legados para backward compat)
  enable_set_business_unit:
    description: '(Legado) Alias para enable_business_unit.'
    required: false
    default: 'false'
  enable_business_unit:
    description: 'Ativa/desativa o vínculo automático do app a UMA Business Unit via REST (true/false).'
    required: false
    default: 'false'
  veracode_business_unit:
    description: 'Nome da Business Unit única a ser atribuída ao app (ex.: "BU TI").'
    required: false
    default: ''
  veracode_policy_name:
    description: 'Nome da policy a ser usada no scan do Veracode.'
    required: false
    default: ''

outputs:
  has_baseline:
    description: 'true/false indicando se o Bantuu possui baseline para o repositório.'
    value: ${{ steps.baseline_flow.outputs.has_baseline || 'false' }}
  pipeline_status:
    description: 'Resumo do caminho seguido: com baseline, sem baseline (com upload), apenas scan ou pipeline desativado.'
    value: ${{ steps.baseline_flow.outputs.pipeline_status || steps.pipeline_only.outputs.pipeline_status || steps.pipeline_disabled_status.outputs.pipeline_status }}
  repository_full_name:
    description: 'Repositório org/repo usado para consultar e enviar baseline ao Bantuu.'
    value: ${{ steps.resolve_repo.outputs.repository_full_name }}

  business_unit_name:
    description: 'Nome da Business Unit aplicada.'
    value: ${{ steps.business_unit.outputs.business_unit_name || '' }}
  business_unit_guid:
    description: 'GUID da Business Unit aplicada.'
    value: ${{ steps.business_unit.outputs.business_unit_guid || '' }}
  set_business_unit_status:
    description: 'Status do passo de vínculo de BU (success | skipped | failed).'
    value: ${{ steps.business_unit.outputs.set_business_unit_status || 'skipped' }}

  sca_status:
    description: 'Resultado do Veracode SCA (success | warning | skipped).'
    value: ${{ steps.veracode_sca.outputs.sca_status || 'skipped' }}
  iac_status:
    description: 'Resultado do Veracode IaC/Secrets (success | failure | skipped).'
    value: ${{ steps.veracode_iac.outputs.iac_status || 'skipped' }}
  upload_scan_status:
    description: 'Resultado do Upload & Scan (success | failure | skipped).'
    value: ${{ steps.upload_and_scan.outcome || 'skipped' }}

runs:
  using: 'composite'
  steps:
    # ── Resolver flag de BU (backward compat) ────────────────────────
    - name: Resolver flag de Business Unit
      id: resolve_bu_flag
      shell: bash
      env:
        FLAG_A: ${{ inputs.enable_business_unit }}
        FLAG_B: ${{ inputs.enable_set_business_unit }}
      run: |
        set -euo pipefail
        if [ "${FLAG_A}" = "true" ] || [ "${FLAG_B}" = "true" ]; then
          echo "enable_bu=true" >> "$GITHUB_OUTPUT"
        else
          echo "enable_bu=false" >> "$GITHUB_OUTPUT"
        fi

    # ── 1. Validar inputs ────────────────────────────────────────────
    - name: Validar inputs
      id: validate
      uses: Afrika-Tecnologia/Veracode-Connect/internal/validate-inputs@v1
      with:
        enable_sca: ${{ inputs.enable_sca }}
        veracode_sca_token: ${{ inputs.veracode_sca_token }}
        enable_iac: ${{ inputs.enable_iac }}
        enable_pipelinescan: ${{ inputs.enable_pipelinescan }}
        enable_baseline: ${{ inputs.enable_baseline }}
        bantuu_api_key: ${{ inputs.bantuu_api_key }}
        bantuu_base_url: ${{ inputs.bantuu_base_url }}
        enable_auto_packager: ${{ inputs.enable_auto_packager }}
        scan_file: ${{ inputs.scan_file }}
        enable_upload_scan: ${{ inputs.enable_upload_scan }}
        enable_business_unit: ${{ steps.resolve_bu_flag.outputs.enable_bu }}
        veracode_business_unit: ${{ inputs.veracode_business_unit }}
        veracode_api_id: ${{ inputs.veracode_api_id }}
        veracode_api_key: ${{ inputs.veracode_api_key }}

    # ── 2. Veracode SCA ──────────────────────────────────────────────
    - name: Veracode SCA
      id: veracode_sca
      if: inputs.enable_sca == 'true'
      uses: Afrika-Tecnologia/Veracode-Connect/internal/veracode-sca@v1
      with:
        veracode_sca_token: ${{ inputs.veracode_sca_token }}

    # ── 3. Veracode IaC / Secrets ────────────────────────────────────
    - name: Veracode IaC / Secrets
      id: veracode_iac
      if: inputs.enable_iac == 'true'
      uses: Afrika-Tecnologia/Veracode-Connect/internal/veracode-iac@v1
      with:
        veracode_api_id: ${{ inputs.veracode_api_id }}
        veracode_api_key: ${{ inputs.veracode_api_key }}

    # ── 4. Preparar scan file (somente se pipeline/upload/baseline precisar) ─
    - name: Preparar scan file
      id: prepare_scan_file
      if: inputs.enable_pipelinescan == 'true' || inputs.enable_upload_scan == 'true' || inputs.enable_baseline == 'true'
      uses: Afrika-Tecnologia/Veracode-Connect/internal/auto-packager@v1
      with:
        enable_auto_packager: ${{ inputs.enable_auto_packager }}
        scan_file: ${{ inputs.scan_file }}

    # ── 5. Resolver nome do repositório ──────────────────────────────
    - name: Resolver nome do repositório
      id: resolve_repo
      uses: Afrika-Tecnologia/Veracode-Connect/internal/resolve-repo@v1

    # ── 6a. Bantuu baseline flow (quando baseline ativo) ─────────────
    - name: Bantuu baseline flow
      id: baseline_flow
      if: inputs.enable_baseline == 'true'
      uses: Afrika-Tecnologia/Veracode-Connect/internal/bantuu-baseline-flow@v1
      with:
        bantuu_api_key: ${{ inputs.bantuu_api_key }}
        bantuu_base_url: ${{ inputs.bantuu_base_url }}
        repository_full_name: ${{ steps.resolve_repo.outputs.repository_full_name }}
        veracode_api_id: ${{ inputs.veracode_api_id }}
        veracode_api_key: ${{ inputs.veracode_api_key }}
        scan_file: ${{ steps.prepare_scan_file.outputs.scan_file }}
        policy_fail: ${{ inputs.policy_fail }}
        fail_on_severity: ${{ inputs.fail_on_severity }}
        veracode_policy_name: ${{ inputs.veracode_policy_name }}

    # ── 6b. Pipeline Scan sem Bantuu (apenas quando baseline desativado) ─
    - name: Pipeline Scan (sem Bantuu)
      id: pipeline_only
      if: inputs.enable_baseline != 'true' && inputs.enable_pipelinescan == 'true'
      uses: Afrika-Tecnologia/Veracode-Connect/internal/pipeline-only@v1
      with:
        veracode_api_id: ${{ inputs.veracode_api_id }}
        veracode_api_key: ${{ inputs.veracode_api_key }}
        scan_file: ${{ steps.prepare_scan_file.outputs.scan_file }}
        policy_fail: ${{ inputs.policy_fail }}
        veracode_policy_name: ${{ inputs.veracode_policy_name }}

    # ── 6c. Pipeline desativado ──────────────────────────────────────
    - name: Pipeline Scan desativado (definir status)
      id: pipeline_disabled_status
      if: inputs.enable_baseline != 'true' && inputs.enable_pipelinescan != 'true'
      shell: bash
      run: |
        set -euo pipefail
        echo "pipeline_status=pipeline_scan_disabled" >> "$GITHUB_OUTPUT"

    # ── 7. Upload & Scan ─────────────────────────────────────────────
    - name: Veracode Upload & Scan
      id: upload_and_scan
      if: (success() || failure()) && inputs.enable_upload_scan == 'true'
      uses: Afrika-Tecnologia/Veracode-Connect/internal/veracode-upload-scan@v1
      with:
        veracode_api_id: ${{ inputs.veracode_api_id }}
        veracode_api_key: ${{ inputs.veracode_api_key }}
        repository_full_name: ${{ steps.resolve_repo.outputs.repository_full_name }}
        veracode_sandbox: ${{ inputs.veracode_sandbox }}
        filepath: ${{ steps.prepare_scan_file.outputs.scan_file }}
        veracode_appname: ${{ inputs.veracode_appname }}

    # ── 8. Business Unit ─────────────────────────────────────────────
    - name: Vincular Business Unit
      id: business_unit
      if: (success() || failure()) && steps.resolve_bu_flag.outputs.enable_bu == 'true'
      uses: Afrika-Tecnologia/Veracode-Connect/internal/veracode-business-unit@v1
      with:
        enable_business_unit: ${{ steps.resolve_bu_flag.outputs.enable_bu }}
        veracode_business_unit: ${{ inputs.veracode_business_unit }}
        veracode_api_id: ${{ inputs.veracode_api_id }}
        veracode_api_key: ${{ inputs.veracode_api_key }}
        veracode_app_name: ${{ inputs.veracode_appname }}
        enable_upload_scan: ${{ inputs.enable_upload_scan }}
        upload_and_scan_outcome: ${{ steps.upload_and_scan.outcome || 'skipped' }}

    # ── 9. Trava de Build (step final obrigatório) ───────────────────
    - name: Trava de Build (verificação final)
      if: always()
      uses: Afrika-Tecnologia/Veracode-Connect/internal/build-gate@v1
      with:
        fail_build: ${{ inputs.fail_build }}
        sca_status: ${{ steps.veracode_sca.outputs.sca_status || 'skipped' }}
        iac_outcome: ${{ steps.veracode_iac.outcome || 'skipped' }}
        baseline_outcome: ${{ steps.baseline_flow.outcome || 'skipped' }}
        pipeline_outcome: ${{ steps.pipeline_only.outcome || 'skipped' }}
        upload_outcome: ${{ steps.upload_and_scan.outcome || 'skipped' }}
        bu_status: ${{ steps.business_unit.outputs.set_business_unit_status || 'skipped' }}