name: 'Veracode SCA'
description: 'Roda o Veracode Software Composition Analysis (SCA) e publica os resultados como artefato.'

inputs:
  veracode_sca_token:
    description: 'Token de API do Veracode SCA (mapeado para SRCCLR_API_TOKEN).'
    required: true

outputs:
  sca_status:
    description: 'Resultado do SCA (success | warning).'
    value: ${{ steps.run_sca.outputs.sca_status }}

runs:
  using: 'composite'
  steps:
    - name: Rodar Veracode SCA
      id: run_sca
      shell: bash
      env:
        SRCCLR_API_TOKEN: ${{ inputs.veracode_sca_token }}
      run: |
        set -euo pipefail

        echo "::group::Veracode SCA"
        set +e
        curl -fsSL --fail-with-body --connect-timeout 30 --max-time 120 --retry 3 --retry-delay 5 https://sca-downloads.veracode.com/ci.sh > ci.sh
        CURL_EXIT="${PIPESTATUS[0]}"

        if [ "${CURL_EXIT}" -ne 0 ]; then
          echo "::error::Falha ao baixar o script SCA do Veracode (curl exit ${CURL_EXIT})."
          exit 1
        fi

        # Verificação simples de tamanho (script não pode ser vazio/muito pequeno)
        if [ ! -s ci.sh ] || [ $(wc -c < ci.sh) -lt 1000 ]; then
          echo "::error::Script ci.sh baixado é inválido ou muito pequeno."
          exit 1
        fi

        bash ci.sh -- scan --allow-dirty 2>&1 | tee veracode_sca.log
        bash_exit="${PIPESTATUS[0]}"
        set -e
        echo "::endgroup::"

        if [ "${bash_exit}" -ne 0 ]; then
          echo "::warning::Veracode SCA retornou exit code ${bash_exit} (o job continua)."
          echo "sca_status=warning" >> "$GITHUB_OUTPUT"
        else
          echo "sca_status=success" >> "$GITHUB_OUTPUT"
        fi

    - name: Upload artefato SCA
      if: always()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: sca-results
        path: |
          veracode_sca.log
        if-no-files-found: warn
