name: 'Bantuu baseline flow'
description: 'Consulta baseline no Bantuu, roda Veracode Pipeline Scan com ou sem baseline, sobe baseline se necessario e publica resultados.'

inputs:
  bantuu_api_key:
    description: 'API Key usada no Bantuu.'
    required: true
  bantuu_base_url:
    description: 'URL base do Bantuu (sem barra final).'
    required: true
  repository_full_name:
    description: 'Repositorio org/repo usado nas chamadas ao Bantuu.'
    required: true
  veracode_api_id:
    description: 'ID da API do Veracode.'
    required: true
  veracode_api_key:
    description: 'Key da API do Veracode.'
    required: true
  scan_file:
    description: 'Arquivo compactado enviado ao Pipeline Scan (ex.: app.zip).'
    required: true
  policy_fail:
    description: 'Define se o scan deve quebrar o build por policy (true/false).'
    required: false
    default: 'false'
  fail_on_severity:
    description: 'Severidades que fazem o scan falhar quando ha baseline (ex.: "Very High, High").'
    required: false
  veracode_policy_name:
    description: 'Nome da policy a ser usada no scan do Veracode.'
    required: false
    default: ''

outputs:
  has_baseline:
    description: 'true/false indicando se o Bantuu possui baseline para o repositorio.'
    value: ${{ steps.check_baseline.outputs.has_baseline }}
  pipeline_status:
    description: 'Resumo do caminho seguido: com baseline ou sem baseline (com upload).'
    value: ${{ steps.pipeline_status_with_baseline.outputs.pipeline_status || steps.pipeline_status_without_baseline.outputs.pipeline_status }}

runs:
  using: 'composite'
  steps:
    - name: Instalar jq (se necessario)
      id: ensure_jq
      shell: bash
      run: |
        set -euo pipefail

        if ! command -v jq >/dev/null 2>&1; then
          sudo apt-get update -y
          sudo apt-get install -y jq
        fi

    - name: Consultar baseline no Bantuu
      id: check_baseline
      shell: bash
      env:
        BANTUU_API_KEY: ${{ inputs.bantuu_api_key }}
        BANTUU_BASE_URL: ${{ inputs.bantuu_base_url }}
        REPOSITORY_FULL_NAME: ${{ inputs.repository_full_name }}
      run: |
        set -euo pipefail

        echo "::group::Bantuu baseline (consulta)"
        RESPONSE_FILE="baseline-response.json"

        HTTP_STATUS=$(curl -sS -w "%{http_code}" -o "${RESPONSE_FILE}" \
          -H "X-API-Key: ${BANTUU_API_KEY}" \
          "${BANTUU_BASE_URL}/api/veracode/baseline?repositoryFullName=${REPOSITORY_FULL_NAME}")

        if [ "${HTTP_STATUS}" -ge 400 ]; then
          echo '{}' > "${RESPONSE_FILE}"
        fi

        if [ ! -s "${RESPONSE_FILE}" ]; then
          echo '{}' > "${RESPONSE_FILE}"
        fi

        HAS_BASELINE=$(jq -r '.hasBaseline // false' "${RESPONSE_FILE}")
        if [ "${HAS_BASELINE}" != "true" ]; then
          HAS_BASELINE="false"
        fi

        echo "has_baseline=${HAS_BASELINE}" >> "$GITHUB_OUTPUT"
        echo "has_baseline=${HAS_BASELINE}"
        echo "::endgroup::"

    - name: Criar arquivo de baseline local a partir do Bantuu
      id: create_local_baseline
      if: steps.check_baseline.outputs.has_baseline == 'true'
      shell: bash
      run: |
        set -euo pipefail
        jq '.results' baseline-response.json > baseline.json

    - name: Rodar Veracode Pipeline Scan com baseline
      id: pipeline_with_baseline
      if: steps.check_baseline.outputs.has_baseline == 'true'
      continue-on-error: true
      uses: veracode/Veracode-pipeline-scan-action@v1.0.20
      with:
        vid: ${{ inputs.veracode_api_id }}
        vkey: ${{ inputs.veracode_api_key }}
        file: ${{ inputs.scan_file }}
        baseline_file: 'baseline.json'
        fail_build: ${{ inputs.policy_fail }}
        fail_on_severity: ${{ inputs.fail_on_severity }}
        json_output: 'true'
        json_output_file: 'results.json'
        veracode_policy_name: ${{ inputs.veracode_policy_name }}

    - name: Enviar resultados do scan com baseline para o Bantuu
      id: upload_baseline_results
      if: steps.check_baseline.outputs.has_baseline == 'true'
      shell: bash
      env:
        BANTUU_API_KEY: ${{ inputs.bantuu_api_key }}
        BANTUU_BASE_URL: ${{ inputs.bantuu_base_url }}
        REPOSITORY_FULL_NAME: ${{ inputs.repository_full_name }}
      run: |
        set -euo pipefail

        echo "::group::Bantuu baseline (upload resultado com baseline)"
        if [ ! -f "results.json" ]; then
          echo "::warning::results.json nao encontrado apos o Pipeline Scan com baseline. Pulando upload."
          echo "::endgroup::"
          exit 0
        fi

        results=$(cat results.json)

        HTTP_STATUS=$(curl -sS -w "%{http_code}" -o /tmp/bantuu-upload-response.txt \
          -X POST "${BANTUU_BASE_URL}/api/veracode/baselineupload?repositoryFullName=${REPOSITORY_FULL_NAME}" \
          -H "Content-Type: application/json" \
          -H "X-API-Key: ${BANTUU_API_KEY}" \
          -d "${results}")

        if [ "${HTTP_STATUS}" -ge 400 ]; then
          echo "::warning::Falha ao enviar resultados com baseline para o Bantuu (HTTP ${HTTP_STATUS}). O job continua."
          cat /tmp/bantuu-upload-response.txt || true
        fi
        echo "::endgroup::"

    - name: Rodar Veracode Pipeline Scan sem baseline
      id: pipeline_without_baseline
      if: steps.check_baseline.outputs.has_baseline == 'false'
      continue-on-error: true
      uses: veracode/Veracode-pipeline-scan-action@v1.0.20
      with:
        vid: ${{ inputs.veracode_api_id }}
        vkey: ${{ inputs.veracode_api_key }}
        file: ${{ inputs.scan_file }}
        fail_build: ${{ inputs.policy_fail }}
        json_output: 'true'
        json_output_file: 'results.json'
        veracode_policy_name: ${{ inputs.veracode_policy_name }}

    - name: Upload artefato Pipeline Scan
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pipescan-results
        path: |
          results.json
          filtered_results.json
        if-no-files-found: warn

    - name: Enviar resultados para o Bantuu (novo baseline)
      id: upload_results
      if: steps.check_baseline.outputs.has_baseline == 'false'
      shell: bash
      env:
        BANTUU_API_KEY: ${{ inputs.bantuu_api_key }}
        BANTUU_BASE_URL: ${{ inputs.bantuu_base_url }}
        REPOSITORY_FULL_NAME: ${{ inputs.repository_full_name }}
      run: |
        set -euo pipefail

        echo "::group::Bantuu baseline (upload)"
        if [ ! -f "results.json" ]; then
          echo "Erro: results.json nao encontrado apos o Pipeline Scan." >&2
          echo "::endgroup::"
          exit 1
        fi

        payload=$(jq -c --arg repo "${REPOSITORY_FULL_NAME}" \
          '. as $scan | {repositoryFullName: $repo, scanResult: $scan}' results.json)

        HTTP_STATUS=$(curl -sS -w "%{http_code}" -o /tmp/bantuu-upload-response.txt \
          -X POST "${BANTUU_BASE_URL}/api/veracode/stock-issues/upload" \
          -H "Content-Type: application/json" \
          -H "X-API-Key: ${BANTUU_API_KEY}" \
          -d "${payload}")

        if [ "${HTTP_STATUS}" -ge 400 ]; then
          echo "Erro ao enviar baseline para Bantuu. Verifique as credenciais." >&2
          cat /tmp/bantuu-upload-response.txt || true
          echo "::endgroup::"
          exit 1
        fi
        echo "::endgroup::"

    - name: Definir status (com baseline)
      id: pipeline_status_with_baseline
      if: steps.check_baseline.outputs.has_baseline == 'true'
      shell: bash
      run: |
        set -euo pipefail
        echo "pipeline_status=scan_completed_with_baseline" >> "$GITHUB_OUTPUT"

    - name: Definir status (sem baseline, baseline enviado)
      id: pipeline_status_without_baseline
      if: steps.check_baseline.outputs.has_baseline == 'false'
      shell: bash
      run: |
        set -euo pipefail
        echo "pipeline_status=scan_completed_without_baseline_and_uploaded" >> "$GITHUB_OUTPUT"

    - name: Verificar resultado do Pipeline Scan (policy_fail)
      if: always()
      shell: bash
      env:
        POLICY_FAIL: ${{ inputs.policy_fail }}
        WITH_BASELINE_OUTCOME: ${{ steps.pipeline_with_baseline.outcome }}
        WITHOUT_BASELINE_OUTCOME: ${{ steps.pipeline_without_baseline.outcome }}
      run: |
        set -euo pipefail

        if [ ! -f "results.json" ]; then
          echo "Erro: results.json nao encontrado apos o Pipeline Scan." >&2
          exit 1
        fi

        outcome="skipped"
        for o in "${WITH_BASELINE_OUTCOME}" "${WITHOUT_BASELINE_OUTCOME}"; do
          if [ -n "${o}" ] && [ "${o}" != "skipped" ]; then
            outcome="${o}"
            break
          fi
        done

        if [ "${outcome}" = "failure" ]; then
          if [ "${POLICY_FAIL}" = "true" ]; then
            echo "Erro: Pipeline Scan falhou e policy_fail=true." >&2
            exit 1
          else
            echo "::warning::Pipeline Scan reportou falhas, mas policy_fail=false (o job continua)."
          fi
        fi
