name: 'Resolver nome do repositorio'
description: 'Resolve o nome completo do repositorio (org/repo) a partir do contexto do GitHub.'

outputs:
  repository_full_name:
    description: 'Repositorio no formato org/repo.'
    value: ${{ steps.resolve.outputs.repository_full_name }}

runs:
  using: 'composite'
  steps:
    - name: Resolver nome do repositorio
      id: resolve
      shell: bash
      run: |
        set -euo pipefail

        echo "::group::Resolver nome do repositorio"
        REPO="${GITHUB_REPOSITORY:-}"

        if [ -z "${REPO}" ]; then
          echo "::error::github.repository nao esta definido no contexto."
          echo "::endgroup::"
          exit 1
        fi

        echo "repository_full_name=${REPO}" >> "$GITHUB_OUTPUT"
        echo "Repositorio: ${REPO}"
        echo "::endgroup::"
