name: 'Validar inputs'
description: 'Valida combinacoes de inputs obrigatorios condicionais antes de executar qualquer scan.'

inputs:
  enable_sca:
    description: 'SCA ativo (true/false).'
    required: true
  veracode_sca_token:
    description: 'Token do Veracode SCA.'
    required: false
  enable_iac:
    description: 'IaC/Secrets ativo (true/false).'
    required: true
  enable_pipelinescan:
    description: 'Pipeline Scan ativo (true/false).'
    required: true
  enable_baseline:
    description: 'Baseline Bantuu ativo (true/false).'
    required: true
  bantuu_api_key:
    description: 'API Key do Bantuu.'
    required: false
  bantuu_base_url:
    description: 'URL base do Bantuu.'
    required: false
    default: ''
  enable_auto_packager:
    description: 'Auto Packager ativo (true/false).'
    required: true
  scan_file:
    description: 'Caminho do artefato compactado.'
    required: false
  enable_upload_scan:
    description: 'Upload & Scan ativo (true/false).'
    required: true
  enable_business_unit:
    description: 'Vinculo de Business Unit ativo (true/false).'
    required: true
  veracode_business_unit:
    description: 'Nome da Business Unit.'
    required: false
  veracode_api_id:
    description: 'ID da API do Veracode.'
    required: true
  veracode_api_key:
    description: 'Key da API do Veracode.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Validar inputs condicionais
      shell: bash
      env:
        ENABLE_SCA: ${{ inputs.enable_sca }}
        SCA_TOKEN: ${{ inputs.veracode_sca_token }}
        ENABLE_IAC: ${{ inputs.enable_iac }}
        ENABLE_PIPELINE: ${{ inputs.enable_pipelinescan }}
        ENABLE_BASELINE: ${{ inputs.enable_baseline }}
        BANTUU_KEY: ${{ inputs.bantuu_api_key }}
        BANTUU_URL: ${{ inputs.bantuu_base_url }}
        ENABLE_AUTO_PACKAGER: ${{ inputs.enable_auto_packager }}
        SCAN_FILE: ${{ inputs.scan_file }}
        ENABLE_UPLOAD: ${{ inputs.enable_upload_scan }}
        ENABLE_BU: ${{ inputs.enable_business_unit }}
        BU_NAME: ${{ inputs.veracode_business_unit }}
        VID: ${{ inputs.veracode_api_id }}
        VKEY: ${{ inputs.veracode_api_key }}
      run: |
        set -euo pipefail
        node "$GITHUB_ACTION_PATH/index.js"
