name: Security Scan (Auto Packager + Baseline + IaC)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auto Packager + Baseline + IaC
        uses: Afrika-Tecnologia/Veracode-Connect@v1
        with:
          bantuu_api_key: ${{ secrets.BANTUU_API_KEY }}
          veracode_api_id: ${{ secrets.VERACODE_API_ID }}
          veracode_api_key: ${{ secrets.VERACODE_API_KEY }}
          enable_auto_packager: 'true'
          enable_baseline: 'true'
          enable_upload_scan: 'false'
          policy_fail: 'false'
          enable_iac: 'true'


