name: 'Veracode IaC / Secrets'
description: 'Roda o Veracode Container/IaC/Secrets scanning (directory scan), coleta resultados e publica como artefato.'

inputs:
  veracode_api_id:
    description: 'ID da API do Veracode (VID).'
    required: true
  veracode_api_key:
    description: 'Key da API do Veracode (VKEY).'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Veracode Container/IaC/Secrets scan (diretorio)
      id: iac_scan
      continue-on-error: true
      uses: veracode/container_iac_secrets_scanning@085755d47439037d39f5686c41b33eaae05dc84b # v1.0.6
      with:
        vid: ${{ inputs.veracode_api_id }}
        vkey: ${{ inputs.veracode_api_key }}
        github-token: ${{ github.token }}
        command: scan
        type: directory
        source: .
        format: table
        fail_build: 'false'
        fail_build_on_error: 'false'

    - name: Coletar arquivos de resultado do IaC
      if: always()
      shell: bash
      run: |
        set -euo pipefail

        echo "::group::Coletar resultados IaC/Secrets"
        mkdir -p iac-results

        files=(
          "results.json"
          "results.txt"
          "sbom_cyclonedx_xml.xml"
          "sbom_cyclonedx_json.json"
          "sbom_spdx_tag_value.json"
          "sbom_spdx_json.json"
          "sbom_github.json"
        )

        moved_any="false"
        for f in "${files[@]}"; do
          if [ -f "${f}" ]; then
            mv -f "${f}" "iac-results/${f}"
            moved_any="true"
          fi
        done

        if [ "${moved_any}" != "true" ]; then
          echo "::warning::Nenhum arquivo de resultado do IaC foi encontrado para coletar."
        else
          echo "Arquivos coletados em iac-results/:"
          ls -la iac-results || true
        fi
        echo "::endgroup::"

    - name: Upload artefato IaC
      if: always()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: iac-results
        path: |
          iac-results
        if-no-files-found: warn
