name: 'Auto Packager'
description: 'Prepara o artefato a ser enviado ao Veracode Pipeline Scan usando a Veracode CLI (Auto Packager) ou um zip informado.'

inputs:
  enable_auto_packager:
    description: 'Ativa/desativa o uso do Veracode Auto Packager (true/false).'
    required: false
    default: 'false'
  scan_file:
    description: 'Caminho do artefato ja empacotado quando o auto packager esta desativado.'
    required: false
  cli_version:
    description: 'Versao da Veracode CLI a ser baixada.'
    required: false
    default: '2.46.0'
  cli_cache_key_prefix:
    description: 'Prefixo para a chave de cache da Veracode CLI.'
    required: false
    default: 'veracode-cli'

outputs:
  scan_file:
    description: 'Caminho efetivo do arquivo a ser usado no Veracode Pipeline Scan.'
    value: ${{ steps.final_output.outputs.scan_file }}

runs:
  using: 'composite'
  steps:
    - name: Configurar Cache da Veracode CLI
      id: cli_cache
      if: inputs.enable_auto_packager == 'true'
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/veracode
        key: ${{ inputs.cli_cache_key_prefix }}-${{ inputs.cli_version }}-${{ runner.os }}

    - name: Preparar scan file (Veracode CLI)
      id: prepare
      shell: bash
      env:
        ENABLE: ${{ inputs.enable_auto_packager }}
        INPUT_SCAN_FILE: ${{ inputs.scan_file }}
        CLI_VERSION: ${{ inputs.cli_version }}
      run: |
        set -euo pipefail

        if [ "${ENABLE}" = "true" ]; then
          echo "::group::Preparar scan file (Auto Packager)"

          if [ -n "${INPUT_SCAN_FILE:-}" ] && [ -f "${INPUT_SCAN_FILE}" ]; then
            echo "::warning::Auto Packager está ativo, mas scan_file foi fornecido. Usando scan_file informado: ${INPUT_SCAN_FILE}"
            echo "scan_file=${INPUT_SCAN_FILE}" >> "$GITHUB_OUTPUT"
            echo "::endgroup::"
            exit 0
          fi

          if [ "${{ steps.cli_cache.outputs.cache-hit }}" != "true" ] && ! command -v veracode >/dev/null 2>&1; then
            curl -fsSL --fail-with-body --connect-timeout 15 --max-time 60 https://tools.veracode.com/veracode-cli/install | VERACODE_CLI_VERSION="${CLI_VERSION}" sh
          fi

          WORKSPACE="${GITHUB_WORKSPACE:-$PWD}"
          if command -v veracode >/dev/null 2>&1; then
            VERACODE_CMD="$(command -v veracode)"
          elif [ -x "${WORKSPACE}/veracode" ]; then
            VERACODE_CMD="${WORKSPACE}/veracode"
            echo "${WORKSPACE}" >> "$GITHUB_PATH"
          elif [ -x "${PWD}/veracode" ]; then
            VERACODE_CMD="${PWD}/veracode"
            echo "${PWD}" >> "$GITHUB_PATH"
          else
            echo "::error::Veracode CLI foi instalada mas o binário 'veracode' não foi encontrado no PATH/workspace."
            echo "::endgroup::"
            exit 1
          fi

          "${VERACODE_CMD}" version || true

          "${VERACODE_CMD}" package discover . || true
          set +e
          "${VERACODE_CMD}" package --trust --source . --type directory --output . 2>&1 | tee veracode_package.log
          PACKAGE_EXIT=${PIPESTATUS[0]}
          set -e

          if [ "${PACKAGE_EXIT}" -ne 0 ]; then
            echo "::warning::'veracode package' retornou exit code ${PACKAGE_EXIT}; tentando fallback."
          fi

          ZIP_FILE="$(sed -n 's/.*Package created: \([^[:space:]]\+\).*/\1/p' veracode_package.log | tail -n 1 || true)"

          if [ -z "${ZIP_FILE:-}" ]; then
            shopt -s nullglob
            zips=( veracode-artifact-*.zip )
            if [ ${#zips[@]} -eq 0 ]; then
              zips=( *.zip )
            fi
            shopt -u nullglob
            if [ ${#zips[@]} -eq 0 ]; then
              echo "::warning::Nenhum arquivo .zip gerado pela Veracode CLI. Acionando fallback (TheDoctor0/zip-release)."
              echo "needs_fallback=true" >> "$GITHUB_OUTPUT"
              echo "::endgroup::"
              exit 0
            fi
            ZIP_FILE="${zips[0]}"
          fi

          if [ ! -f "${ZIP_FILE}" ]; then
            echo "::error::Arquivo '${ZIP_FILE}' não encontrado após o Auto Packager."
            echo "::endgroup::"
            exit 1
          fi

          TARGET="app.zip"

          if [ "${TARGET}" != "${ZIP_FILE}" ]; then
            cp "${ZIP_FILE}" "${TARGET}"
          fi

          echo "Criado app.zip:"
          ls -lh "${TARGET}" || true
          echo "scan_file=${TARGET}" >> "$GITHUB_OUTPUT"
          echo "::endgroup::"
        else
          if [ -z "${INPUT_SCAN_FILE}" ]; then
            echo "::error::scan_file não foi fornecido e enable_auto_packager está 'false'."
            exit 1
          fi

          if [ ! -f "${INPUT_SCAN_FILE}" ]; then
            echo "::error::Arquivo '${INPUT_SCAN_FILE}' não encontrado."
            exit 1
          fi

        fi

    - name: Fallback ZIP (zip-release)
      if: steps.prepare.outputs.needs_fallback == 'true'
      uses: TheDoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657 # v0.7.6
      with:
        type: 'zip'
        filename: 'app.zip'
        exclusions: '*.git* /*node_modules/* veracode veracode.exe veracode-cli_* app.zip results.json filtered_results.json baseline.json baseline-response.json veracode_*.log iac-results/* .next/* dist/* build/* target/* .gradle/* __pycache__/* *.pyc *.class coverage/* .cache/* .pytest_cache/* *.log bin/* obj/*'

    - name: Concluir Fallback ZIP
      if: steps.prepare.outputs.needs_fallback == 'true'
      shell: bash
      run: |
        echo "Criado app.zip via TheDoctor0/zip-release (fallback):"
        ls -lh app.zip || true
        echo "scan_file=app.zip" >> "$GITHUB_OUTPUT"
      id: fallback_output

    - name: Consolidar Saida
      id: final_output
      shell: bash
      env:
        PREP_FILE: ${{ steps.prepare.outputs.scan_file }}
        FALL_FILE: ${{ steps.fallback_output.outputs.scan_file }}
      run: |
        if [ -n "${FALL_FILE:-}" ]; then
          echo "scan_file=${FALL_FILE}" >> "$GITHUB_OUTPUT"
        else
          echo "scan_file=${PREP_FILE}" >> "$GITHUB_OUTPUT"
        fi
