name: 'Auto Packager'
description: 'Prepara o artefato a ser enviado ao Veracode Pipeline Scan usando a Veracode CLI (Auto Packager) ou um zip informado.'

inputs:
  enable_auto_packager:
    description: 'Ativa/desativa o uso do Veracode Auto Packager (true/false).'
    required: false
    default: 'false'
  scan_file:
    description: 'Caminho do artefato ja empacotado quando o auto packager esta desativado.'
    required: false

outputs:
  scan_file:
    description: 'Caminho efetivo do arquivo a ser usado no Veracode Pipeline Scan.'
    value: ${{ steps.prepare.outputs.scan_file }}

runs:
  using: 'composite'
  steps:
    - name: Preparar scan file
      id: prepare
      shell: bash
      env:
        ENABLE: ${{ inputs.enable_auto_packager }}
        INPUT_SCAN_FILE: ${{ inputs.scan_file }}
      run: |
        set -euo pipefail

        if [ "${ENABLE}" = "true" ]; then
          echo "::group::Preparar scan file (Auto Packager)"

          if [ -n "${INPUT_SCAN_FILE:-}" ] && [ -f "${INPUT_SCAN_FILE}" ]; then
            echo "::warning::Auto Packager esta ativo, mas scan_file foi fornecido. Usando scan_file informado: ${INPUT_SCAN_FILE}"
            echo "scan_file=${INPUT_SCAN_FILE}" >> "$GITHUB_OUTPUT"
            echo "::endgroup::"
            exit 0
          fi

          if ! command -v veracode >/dev/null 2>&1; then
            curl -fsS https://tools.veracode.com/veracode-cli/install | VERACODE_CLI_VERSION=2.46.0 sh
          fi

          WORKSPACE="${GITHUB_WORKSPACE:-$PWD}"
          if command -v veracode >/dev/null 2>&1; then
            VERACODE_CMD="$(command -v veracode)"
          elif [ -x "${WORKSPACE}/veracode" ]; then
            VERACODE_CMD="${WORKSPACE}/veracode"
            echo "${WORKSPACE}" >> "$GITHUB_PATH"
          elif [ -x "${PWD}/veracode" ]; then
            VERACODE_CMD="${PWD}/veracode"
            echo "${PWD}" >> "$GITHUB_PATH"
          else
            echo "::error::Veracode CLI foi instalada mas o binario 'veracode' nao foi encontrado no PATH/workspace."
            echo "::endgroup::"
            exit 1
          fi

          "${VERACODE_CMD}" version || true

          "${VERACODE_CMD}" package discover . || true
          set +e
          "${VERACODE_CMD}" package --trust --source . --type directory --output . 2>&1 | tee veracode_package.log
          PACKAGE_EXIT=${PIPESTATUS[0]}
          set -e

          if [ "${PACKAGE_EXIT}" -ne 0 ]; then
            echo "::warning::'veracode package' retornou exit code ${PACKAGE_EXIT}; tentando fallback."
          fi

          ZIP_FILE="$(sed -n 's/.*Package created: \([^[:space:]]\+\).*/\1/p' veracode_package.log | tail -n 1 || true)"

          if [ -z "${ZIP_FILE:-}" ]; then
            shopt -s nullglob
            zips=( veracode-artifact-*.zip )
            if [ ${#zips[@]} -eq 0 ]; then
              zips=( *.zip )
            fi
            shopt -u nullglob
            if [ ${#zips[@]} -eq 0 ]; then
              echo "::warning::Nenhum arquivo .zip gerado pela Veracode CLI (Auto Packager). Gerando app.zip via 'zip' (fallback)."

              if ! command -v zip >/dev/null 2>&1; then
                sudo apt-get update -y
                sudo apt-get install -y zip
              fi

              rm -f app.zip
              zip -rq app.zip . \
                -x ".git/*" ".github/*" \
                -x "node_modules/*" "*/node_modules/*" "*/*/node_modules/*" "*/*/*/node_modules/*" \
                -x "veracode" "veracode.exe" "veracode-cli_*" \
                -x "app.zip" \
                -x "results.json" "filtered_results.json" "baseline.json" "baseline-response.json" \
                -x "veracode_package.log" "veracode_sca.log" "veracode_iac.log"

              echo "Criado app.zip (fallback):"
              ls -lh app.zip || true
              echo "scan_file=app.zip" >> "$GITHUB_OUTPUT"
              echo "::endgroup::"
              exit 0
            fi
            ZIP_FILE="${zips[0]}"
          fi

          if [ ! -f "${ZIP_FILE}" ]; then
            echo "::error::Arquivo '${ZIP_FILE}' nao encontrado apos o Auto Packager."
            echo "::endgroup::"
            exit 1
          fi

          TARGET="app.zip"

          if [ "${TARGET}" != "${ZIP_FILE}" ]; then
            cp "${ZIP_FILE}" "${TARGET}"
          fi

          echo "Criado app.zip:"
          ls -lh "${TARGET}" || true
          echo "scan_file=${TARGET}" >> "$GITHUB_OUTPUT"
          echo "::endgroup::"
        else
          if [ -z "${INPUT_SCAN_FILE}" ]; then
            echo "::error::scan_file nao foi fornecido e enable_auto_packager esta 'false'."
            exit 1
          fi

          if [ ! -f "${INPUT_SCAN_FILE}" ]; then
            echo "::error::Arquivo '${INPUT_SCAN_FILE}' nao encontrado."
            exit 1
          fi

          echo "scan_file=${INPUT_SCAN_FILE}" >> "$GITHUB_OUTPUT"
        fi
