name: 'Veracode Pipeline Scan (sem Bantuu)'
description: 'Roda apenas o Veracode Pipeline Scan sem integrar com o Bantuu e publica resultados.'

inputs:
  veracode_api_id:
    description: 'ID da API do Veracode.'
    required: true
  veracode_api_key:
    description: 'Key da API do Veracode.'
    required: true
  scan_file:
    description: 'Arquivo compactado enviado ao Pipeline Scan (ex.: app.zip).'
    required: true
  policy_fail:
    description: 'Define se o scan deve quebrar o build por policy (true/false).'
    required: false
    default: 'false'
  veracode_policy_name:
    description: 'Nome da policy a ser usada no scan do Veracode.'
    required: false
    default: ''

outputs:
  pipeline_status:
    description: 'Resumo do caminho seguido para o scan sem Bantuu.'
    value: ${{ steps.pipeline_status.outputs.pipeline_status }}

runs:
  using: 'composite'
  steps:
    - name: Rodar Veracode Pipeline Scan
      id: pipeline_only
      uses: veracode/Veracode-pipeline-scan-action@d7c19ef9f6584f1a729ce0a3ae106e5a6840548e # v1.0.20
      with:
        vid: ${{ inputs.veracode_api_id }}
        vkey: ${{ inputs.veracode_api_key }}
        file: ${{ inputs.scan_file }}
        fail_build: ${{ inputs.policy_fail }}
        json_output: 'true'
        json_output_file: 'results.json'
        veracode_policy_name: ${{ inputs.veracode_policy_name }}

    - name: Upload artefato Pipeline Scan
      if: steps.pipeline_only.outcome != 'skipped'
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: pipescan-results
        path: |
          results.json
          filtered_results.json
        if-no-files-found: warn

    - name: Definir status do pipeline
      id: pipeline_status
      shell: bash
      run: |
        set -euo pipefail
        echo "pipeline_status=scan_completed_without_bantuu" >> "$GITHUB_OUTPUT"

    - name: Verificar resultado do Pipeline Scan (policy_fail)
      if: steps.pipeline_only.outcome != 'skipped'
      shell: bash
      env:
        POLICY_FAIL: ${{ inputs.policy_fail }}
        PIPELINE_OUTCOME: ${{ steps.pipeline_only.outcome }}
      run: |
        set -euo pipefail

        if [ ! -f "results.json" ]; then
          echo "::error::results.json nao encontrado apos o Pipeline Scan."
          exit 1
        fi

        if [ "${PIPELINE_OUTCOME}" = "failure" ]; then
          if [ "${POLICY_FAIL}" = "true" ]; then
            echo "::error::Pipeline Scan falhou e policy_fail=true."
            exit 1
          else
            echo "::warning::Pipeline Scan reportou falhas, mas policy_fail=false (o job continua)."
          fi
        fi
